# Generated by Django 5.2.6 on 2026-01-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(help_text='Dominio principal, ej: example.com', max_length=255)),
                ('gsc_property', models.CharField(blank=True, default='', help_text='GSC property URL, ej: sc-domain:example.com o https://example.com/', max_length=255)),
                ('ga4_property_id', models.CharField(blank=True, default='', help_text='GA4 property id (solo el número), ej: 123456789', max_length=50)),
                ('ads_customer_id', models.CharField(blank=True, default='', help_text='Google Ads customer id, ej: 123-456-7890 (obligatorio para Keyword Research)', max_length=50)),
                ('country_code', models.CharField(default='ES', help_text='ISO2, ej: ES', max_length=2)),
                ('language_code', models.CharField(default='es', help_text='ej: es, en', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
            ],
            options={
                'unique_together': {('client', 'name')},
            },
        ),
    ]
