# Generated by Django 5.2.6 on 2026-01-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('domain', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=10)),
                ('google_ads_customer_id', models.CharField(blank=True, default='', max_length=32)),
                ('gsc_site_url', models.CharField(blank=True, default='', help_text='Search Console property. Ejemplo: sc-domain:example.com o https://example.com/', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.client')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.language')),
            ],
            options={
                'ordering': ['client__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('device', models.CharField(blank=True, default='', max_length=10)),
                ('target_url', models.URLField(blank=True, default='')),
                ('intent', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1=low cost, 5=high priority')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='projects.project')),
            ],
            options={
                'ordering': ['project__client__name', 'project__name', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_domain', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['domain'], name='projects_pr_domain_9de146_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('client', 'domain'), name='uniq_client_domain'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['project', 'status'], name='projects_ke_project_6f57e6_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['keyword'], name='projects_ke_keyword_439ee8_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('project', 'keyword', 'country', 'city', 'language', 'device'), name='uniq_keyword_scope'),
        ),
        migrations.AddIndex(
            model_name='projectcompetitor',
            index=models.Index(fields=['project', 'competitor_domain'], name='projects_pr_project_b18bb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcompetitor',
            constraint=models.UniqueConstraint(fields=('project', 'competitor_domain'), name='uniq_competitor_per_project'),
        ),
    ]
