# Generated by Django 5.2.6 on 2026-01-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ads_manager_customer_id',
            field=models.CharField(blank=True, help_text='Opcional. CID del MCC/Manager (ej 5110999249). Si se define, SEOSuite enviará login-customer-id.', max_length=32, null=True),
        ),
    ]
