# Generated by Django 5.2.6 on 2026-01-03 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_gads_login_customer_id_and_more'),
        ('geo', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='google_ads_customer_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gsc_site_url',
        ),
        migrations.AddField(
            model_name='project',
            name='gads_login_customer_id',
            field=models.CharField(blank=True, default='', help_text='Google Ads login customer id (sin guiones). Ej: 1234567890', max_length=32, verbose_name='Gads login customer id'),
        ),
        migrations.AddField(
            model_name='project',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Google analytics id'),
        ),
        migrations.AddField(
            model_name='project',
            name='gsc_website_link',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='Gsc website link'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(help_text='Ejemplo: voicesenglish.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nombre del projecto'),
        ),
    ]
