# Generated by Django 5.2.6 on 2026-01-03 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_keyword_state_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='GscRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('query', models.TextField(blank=True, default='')),
                ('page', models.URLField(blank=True, default='', max_length=2048)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('device', models.CharField(blank=True, default='', max_length=20)),
                ('clicks', models.FloatField(blank=True, null=True)),
                ('impressions', models.FloatField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('position', models.FloatField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_rows', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['project', 'date'], name='projects_gs_project_74586a_idx'), models.Index(fields=['project', 'query'], name='projects_gs_project_c78eaa_idx'), models.Index(fields=['project', 'page'], name='projects_gs_project_876b54_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'date', 'query', 'page', 'country', 'device'), name='uniq_gscrow_project_date_dims')],
            },
        ),
        migrations.CreateModel(
            name='GscSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=2048)),
                ('date', models.DateField()),
                ('dimensions_json', models.JSONField(blank=True, default=list)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(default=0)),
                ('cost_units', models.PositiveIntegerField(default=0)),
                ('cache_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('rows_fetched', models.PositiveIntegerField(default=0)),
                ('rows_upserted', models.PositiveIntegerField(default=0)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_sync_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['project', 'date'], name='projects_gs_project_71e4f4_idx'), models.Index(fields=['status', 'requested_at'], name='projects_gs_status_eafa6d_idx'), models.Index(fields=['cache_key', 'cache_expires_at'], name='projects_gs_cache_k_784eaa_idx')],
            },
        ),
    ]
