# Generated by Django 5.2.6 on 2026-01-03 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('internal', 'Internal'), ('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('ads', 'Google Ads'), ('serpapi', 'SerpAPI'), ('dataforseo', 'DataForSEO')], default='internal', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('cost_micros', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('entity_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('entity_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='internal', max_length=30)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, default='')),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_responses', to='core.run')),
            ],
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artifact_type', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF'), ('text', 'Text'), ('other', 'Other')], default='other', max_length=20)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.run')),
            ],
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['provider', 'kind', 'input_hash'], name='core_run_provide_a79902_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'created_at'], name='core_run_status_4b4dbe_idx'),
        ),
    ]
