# Generated by Django 6.0 on 2026-01-02 00:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('serpapi', 'SerpAPI'), ('dataforseo', 'DataForSEO')], default='mock', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('device', models.CharField(blank=True, default='', max_length=10)),
                ('top_n', models.PositiveIntegerField(default=10)),
                ('total_keywords', models.PositiveIntegerField(default=0)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_runs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('result_type', models.CharField(choices=[('organic', 'Organic'), ('ad', 'Ad'), ('feature', 'Feature')], default='organic', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('url', models.URLField(blank=True, default='', max_length=600)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('snippet', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='core.keyword')),
                ('serp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.serprun')),
            ],
            options={
                'ordering': ['keyword_id', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='serprun',
            index=models.Index(fields=['project', 'created_at'], name='core_serpru_project_b9b3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='serprun',
            index=models.Index(fields=['status', 'created_at'], name='core_serpru_status_08335e_idx'),
        ),
        migrations.AddIndex(
            model_name='serpresult',
            index=models.Index(fields=['serp_run', 'keyword'], name='core_serpre_serp_ru_a75c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='serpresult',
            index=models.Index(fields=['domain'], name='core_serpre_domain_4f0cbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='serpresult',
            constraint=models.UniqueConstraint(fields=('serp_run', 'keyword', 'position', 'result_type'), name='uniq_serpresult_position'),
        ),
    ]
