# Generated by Django 6.0 on 2026-01-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serprun_serpresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serprun',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
