# Generated by Django 6.0 on 2026-01-02 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serprun_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpKeywordSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_domain', models.CharField(max_length=255)),
                ('tracked_position', models.PositiveIntegerField(blank=True, null=True)),
                ('top_domain', models.CharField(blank=True, default='', max_length=255)),
                ('top_position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.keyword')),
                ('serp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.serprun')),
            ],
            options={
                'ordering': ['keyword_id'],
                'indexes': [models.Index(fields=['serp_run', 'keyword'], name='core_serpke_serp_ru_5ad0ca_idx'), models.Index(fields=['tracked_domain'], name='core_serpke_tracked_1818d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('serp_run', 'keyword'), name='uniq_snapshot_per_run_keyword')],
            },
        ),
    ]
