# Generated by Django 6.0 on 2026-01-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serpkeywordsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='serpkeywordsnapshot',
            name='top_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
