# Generated by Django 6.0 on 2026-01-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_serpkeywordsnapshot_top_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serpkeywordsnapshot',
            name='top3_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serpkeywordsnapshot',
            name='top3_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
