# Generated by Django 5.2.6 on 2026-01-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serpkeywordsnapshot_top3_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serprun',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serprun',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serpkeywordsnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serpresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serprun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serprun',
            name='provider',
            field=models.CharField(default='serpapi', max_length=30),
        ),
        migrations.AlterField(
            model_name='serprun',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serprun',
            name='status',
            field=models.CharField(default='created', max_length=30),
        ),
    ]
