# Generated by Django 5.2.6 on 2026-01-03 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa solo números y caracteres + ( ) . - y espacios.', regex='^\\+?[0-9\\s().-]{7,20}$')]),
        ),
    ]
