# Generated by Django 5.2.6 on 2026-01-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_contact_email_client_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gads_login_customer_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='google_analytics_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gsc_website_link',
        ),
    ]
