# Generated by Django 5.2.6 on 2026-01-04 00:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('locale', models.CharField(help_text='Ej: ES-es', max_length=20)),
                ('language', models.CharField(help_text='Ej: es', max_length=10)),
                ('geo', models.CharField(help_text='Geo target resource_name o id', max_length=255)),
                ('avg_monthly_searches', models.IntegerField(blank=True, null=True)),
                ('cpc_micros', models.BigIntegerField(blank=True, null=True)),
                ('competition_level', models.CharField(blank=True, default='', help_text='LOW/MEDIUM/HIGH/UNSPECIFIED (según provider)', max_length=20)),
                ('source', models.CharField(default='ads', max_length=30)),
                ('source_confidence', models.FloatField(default=0.9)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_metrics', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_metrics', to='core.run')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'keyword'], name='keyword_res_project_b05126_idx'), models.Index(fields=['run', 'keyword'], name='keyword_res_run_id_0b919c_idx'), models.Index(fields=['locale', 'language'], name='keyword_res_locale_6b451e_idx')],
            },
        ),
    ]
