# Generated by Django 5.2.6 on 2026-01-03 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('planner', '0003_fix_keyword_indexes'),
        ('projects', '0003_remove_keyword_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordidearun',
            name='cache_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='cache_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='cost_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='response_status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='KeywordMetricsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('dataforseo', 'DataForSEO')], default='dataforseo', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('location_code', models.IntegerField(default=2840)),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(default=0)),
                ('cost_units', models.PositiveIntegerField(default=0)),
                ('cache_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('keywords_count', models.PositiveIntegerField(default=0)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_metrics_runs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('competition', models.CharField(blank=True, default='', max_length=10)),
                ('competition_index', models.IntegerField(blank=True, null=True)),
                ('cpc', models.FloatField(blank=True, null=True)),
                ('low_top_of_page_bid', models.FloatField(blank=True, null=True)),
                ('high_top_of_page_bid', models.FloatField(blank=True, null=True)),
                ('monthly_searches', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='planner.keyword')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='planner.keywordmetricsrun')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('keyword', 'Keyword'), ('domain', 'Domain'), ('url', 'URL')], default='keyword', max_length=10)),
                ('seed', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('device', models.CharField(blank=True, default='desktop', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_seeds', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='keywordidearun',
            name='seed_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.keywordseed'),
        ),
        migrations.AddIndex(
            model_name='keywordidearun',
            index=models.Index(fields=['cache_key', 'cache_expires_at'], name='planner_key_cache_k_9e016b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidearun',
            index=models.Index(fields=['status', 'requested_at'], name='planner_key_status_ee855c_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordmetricsrun',
            index=models.Index(fields=['project', 'requested_at'], name='planner_key_project_c34973_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordmetricsrun',
            index=models.Index(fields=['status', 'requested_at'], name='planner_key_status_16bbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordmetricsrun',
            index=models.Index(fields=['cache_key', 'cache_expires_at'], name='planner_key_cache_k_a739cd_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordmetricsnapshot',
            index=models.Index(fields=['keyword'], name='planner_key_keyword_bcb17c_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordmetricsnapshot',
            index=models.Index(fields=['search_volume'], name='planner_key_search__ab8b7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='keywordmetricsnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'keyword'), name='uniq_kw_metric_snapshot_per_run'),
        ),
        migrations.AddIndex(
            model_name='keywordseed',
            index=models.Index(fields=['project', 'created_at'], name='planner_key_project_306d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordseed',
            index=models.Index(fields=['seed'], name='planner_key_seed_bd1eb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='keywordseed',
            constraint=models.UniqueConstraint(fields=('project', 'kind', 'seed', 'country', 'city', 'language', 'device'), name='uniq_keyword_seed_scope'),
        ),
    ]
