# Generated by Django 5.2.6 on 2026-01-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('ads', 'Google Ads')], max_length=20)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('pass', 'Pass'), ('fail', 'Fail')], default='unknown', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.run')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_statuses', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'provider', 'status'], name='integration_project_d29c53_idx')],
                'unique_together': {('project', 'provider')},
            },
        ),
    ]
