# Generated by Django 5.2.6 on 2026-01-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationstatus',
            name='ads_mode',
            field=models.CharField(choices=[('direct', 'Direct account'), ('manager', 'Manager (MCC)')], default='direct', help_text='Ads access mode. DIRECT uses project.ads_customer_id. MANAGER uses login_customer_id (MCC).', max_length=16),
        ),
        migrations.AddField(
            model_name='integrationstatus',
            name='login_customer_id',
            field=models.CharField(blank=True, default='', help_text='Manager (MCC) customer id, required if ads_mode=manager.', max_length=32),
        ),
    ]
