# Generated by Django 5.2.6 on 2026-01-02 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='serpapi', max_length=30)),
                ('status', models.CharField(default='created', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('device', models.CharField(blank=True, default='', max_length=10)),
                ('top_n', models.PositiveIntegerField(default=10)),
                ('total_keywords', models.PositiveIntegerField(default=0)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('result_type', models.CharField(choices=[('organic', 'Organic'), ('ad', 'Ad'), ('feature', 'Feature')], default='organic', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('url', models.URLField(blank=True, default='', max_length=600)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('snippet', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='projects.keyword')),
                ('serp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='serp.serprun')),
            ],
            options={
                'ordering': ['keyword_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SerpKeywordSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_domain', models.CharField(max_length=255)),
                ('tracked_position', models.PositiveIntegerField(blank=True, null=True)),
                ('top_domain', models.CharField(blank=True, default='', max_length=255)),
                ('top_position', models.PositiveIntegerField(blank=True, null=True)),
                ('top_url', models.URLField(blank=True, default='', max_length=600)),
                ('top3_domains', models.JSONField(blank=True, default=list)),
                ('top3_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.keyword')),
                ('serp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='serp.serprun')),
            ],
            options={
                'ordering': ['keyword_id'],
            },
        ),
        migrations.CreateModel(
            name='SerpFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=50)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='serp.serprun')),
            ],
            options={
                'ordering': ['serp_run_id', 'feature_type'],
            },
        ),
        migrations.AddIndex(
            model_name='serprun',
            index=models.Index(fields=['project', 'created_at'], name='serp_serpru_project_5a47a5_idx'),
        ),
        migrations.AddIndex(
            model_name='serprun',
            index=models.Index(fields=['status', 'created_at'], name='serp_serpru_status_b94b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='serpresult',
            index=models.Index(fields=['serp_run', 'keyword'], name='serp_serpre_serp_ru_688219_idx'),
        ),
        migrations.AddIndex(
            model_name='serpresult',
            index=models.Index(fields=['domain'], name='serp_serpre_domain_09fbb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='serpresult',
            constraint=models.UniqueConstraint(fields=('serp_run', 'keyword', 'position', 'result_type'), name='uniq_serpresult_position'),
        ),
        migrations.AddIndex(
            model_name='serpkeywordsnapshot',
            index=models.Index(fields=['serp_run', 'keyword'], name='serp_serpke_serp_ru_d9eb55_idx'),
        ),
        migrations.AddIndex(
            model_name='serpkeywordsnapshot',
            index=models.Index(fields=['tracked_domain'], name='serp_serpke_tracked_0624b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='serpkeywordsnapshot',
            constraint=models.UniqueConstraint(fields=('serp_run', 'keyword'), name='uniq_snapshot_per_run_keyword'),
        ),
        migrations.AddIndex(
            model_name='serpfeature',
            index=models.Index(fields=['serp_run', 'feature_type'], name='serp_serpfe_serp_ru_0a10e2_idx'),
        ),
    ]
