# Generated by Django 5.2.6 on 2026-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('projects', '0001_initial'),
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serprun',
            name='cache_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serprun',
            name='cache_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='serprun',
            name='cost_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serprun',
            name='response_status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serprun',
            name='run_type',
            field=models.CharField(blank=True, default='rank_tracking', max_length=40),
        ),
        migrations.AddIndex(
            model_name='serprun',
            index=models.Index(fields=['cache_key', 'cache_expires_at'], name='serp_serpru_cache_k_e31864_idx'),
        ),
        migrations.AddIndex(
            model_name='serprun',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='serp_serpru_provide_83e2fe_idx'),
        ),
    ]
