# Generated by Django 5.2.6 on 2026-01-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('dataforseo_location_code', models.IntegerField(blank=True, help_text='DataForSEO location_code (numérico). Ej: 2840 = United States', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('google_ads_language_id', models.IntegerField(blank=True, help_text='Google Ads language constant ID', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
