# Generated by Django 5.2.6 on 2026-01-02 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordIdeaRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_keyword', models.CharField(max_length=255)),
                ('location_code', models.IntegerField(default=2840)),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('provider', models.CharField(choices=[('google_ads', 'Google Ads'), ('dataforseo', 'DataForSEO'), ('dataforseo_labs', 'DataForSEO Labs')], default='dataforseo', max_length=32)),
                ('from_cache', models.BooleanField(default=False)),
                ('is_new_seed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_idea_runs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.IntegerField(default=0)),
                ('competition_index', models.IntegerField(blank=True, null=True)),
                ('low_top_of_page_bid', models.FloatField(blank=True, null=True)),
                ('high_top_of_page_bid', models.FloatField(blank=True, null=True)),
                ('cpc', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='planner.keywordidearun')),
            ],
        ),
        migrations.AddIndex(
            model_name='keywordidearun',
            index=models.Index(fields=['project', 'created_at'], name='planner_key_project_2d10ac_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidearun',
            index=models.Index(fields=['project', 'seed_keyword', 'location_code', 'language_code'], name='planner_key_project_d5c136_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidearun',
            index=models.Index(fields=['project', 'is_new_seed', 'created_at'], name='planner_key_project_2fa622_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidea',
            index=models.Index(fields=['keyword'], name='planner_key_keyword_88a6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidea',
            index=models.Index(fields=['search_volume'], name='planner_key_search__5a7b7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='keywordidea',
            constraint=models.UniqueConstraint(fields=('run', 'keyword'), name='uniq_keyword_idea_per_run'),
        ),
    ]
